# Help:  https://aka.ms/yaml

resources:
- repo: self

variables:  []

trigger:
- master

stages:
  - stage:  build
    dependsOn:  []
    variables:  []
    jobs:
    - job:  move-templates
      dependsOn:  []
      variables:  []
      continueOnError:  false
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      # Copy source to "content" folder
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/content'
        inputs:
          TargetFolder: '$(Build.ArtifactStagingDirectory)/content'

      # Publish "content" artefact
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: content'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/content'
          ArtifactName: content
  - stage:  release-prod
    dependsOn:  []
    variables:  []
    jobs:
    - job:  deployment
      dependsOn:  []
        variables:
          location: northcentralus
          rg: blog
      continueOnError:  false
      pool:
        vmImage: ubuntu-latest
      steps:
        steps:
        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment - Main'
          inputs:
            azureSubscription: 'devops-deploy'
            resourceGroupName: '$(rg)'
            location: '$(location)'
            csmFile: '$(System.DefaultWorkingDirectory)/shared-infra/content/deploy.json'
            csmParametersFile: '$(System.DefaultWorkingDirectory)/shared-infra/content/deploy.prod.parameters.json'
            overrideParameters: ''
          timeoutInMinutes: 3
